# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SpeechToText.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpeechToTextDialog(object):
    def setupUi(self, SpeechToTextDialog):
        SpeechToTextDialog.setObjectName("SpeechToTextDialog")
        SpeechToTextDialog.resize(415, 236)
        self.StartPushButton = QtWidgets.QPushButton(SpeechToTextDialog)
        self.StartPushButton.setGeometry(QtCore.QRect(20, 190, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.StartPushButton.setFont(font)
        self.StartPushButton.setObjectName("StartPushButton")
        self.PausePushButton = QtWidgets.QPushButton(SpeechToTextDialog)
        self.PausePushButton.setGeometry(QtCore.QRect(170, 190, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.PausePushButton.setFont(font)
        self.PausePushButton.setObjectName("PausePushButton")
        self.langCombo = QtWidgets.QComboBox(SpeechToTextDialog)
        self.langCombo.setGeometry(QtCore.QRect(80, 10, 310, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.langCombo.setFont(font)
        self.langCombo.setObjectName("langCombo")
        self.SpeechTextEdit = QtWidgets.QTextEdit(SpeechToTextDialog)
        self.SpeechTextEdit.setGeometry(QtCore.QRect(20, 40, 371, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpeechTextEdit.setFont(font)
        self.SpeechTextEdit.setObjectName("SpeechTextEdit")
        self.StopPushButton = QtWidgets.QPushButton(SpeechToTextDialog)
        self.StopPushButton.setGeometry(QtCore.QRect(317, 190, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.StopPushButton.setFont(font)
        self.StopPushButton.setObjectName("StopPushButton")
        self.label = QtWidgets.QLabel(SpeechToTextDialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ExportPathTextEdit = QtWidgets.QTextEdit(SpeechToTextDialog)
        self.ExportPathTextEdit.setGeometry(QtCore.QRect(90, 140, 270, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ExportPathTextEdit.setFont(font)
        self.ExportPathTextEdit.setObjectName("ExportPathTextEdit")
        self.BrowserPushButton = QtWidgets.QPushButton(SpeechToTextDialog)
        self.BrowserPushButton.setGeometry(QtCore.QRect(360, 140, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BrowserPushButton.setFont(font)
        self.BrowserPushButton.setObjectName("BrowserPushButton")
        self.ExportCheckBox = QtWidgets.QCheckBox(SpeechToTextDialog)
        self.ExportCheckBox.setGeometry(QtCore.QRect(20, 150, 70, 17))
        self.ExportCheckBox.setObjectName("ExportCheckBox")

        self.retranslateUi(SpeechToTextDialog)
        QtCore.QMetaObject.connectSlotsByName(SpeechToTextDialog)

    def retranslateUi(self, SpeechToTextDialog):
        _translate = QtCore.QCoreApplication.translate
        SpeechToTextDialog.setWindowTitle(_translate("SpeechToTextDialog", "Dialog"))
        self.StartPushButton.setText(_translate("SpeechToTextDialog", "Start"))
        self.PausePushButton.setText(_translate("SpeechToTextDialog", "Pause"))
        self.StopPushButton.setText(_translate("SpeechToTextDialog", "Stop"))
        self.label.setText(_translate("SpeechToTextDialog", "Language : "))
        self.BrowserPushButton.setText(_translate("SpeechToTextDialog", "..."))
        self.ExportCheckBox.setText(_translate("SpeechToTextDialog", "Export To "))
